# Menu Options Configuration
MainMenu:
  title: Discogs Library Dumper
  options: [
        'Dump Discogs Library to Excel File',
        'Dump Discogs Library to CSV File',
        'Show Library Statistics',
        'Configure Login Data',
        'Exit'
    ]
LoginData:
  title:
  options: [
        'Change username'
        'Change apitoken'
    ]
