# General Configuration
Login:
  username: #buntstift
  apitoken: #rFqYEhGrrhMSuVDppFVXJhAqktGMYUGseliaRInk
API:
  api_base_url: https://api.discogs.com
  format: = "application/vnd.discogs.v2.plaintext+json"
  limit: = 100
  convertion_ratio: = 20
  https_base_url: = https://www.discogs.com/
  release_url: https://api.discogs.com/users/{username}/collection/folders/0/releases/
  headers:
    Accept: application/vnd.discogs.v2.plaintext+json
    Content-Type: application/json
    User-Agent: Dump Library/1.1 +https://github.com/blackbunt/dump-discogs-collection-2-csv
  params:
    page: 1
    per_page: 1
    token:

